// Code generated by "stringer -type=State,Action -linecomment -output=types_string.go"; DO NOT EDIT.

package prbf2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateStopped-0]
	_ = x[StateStopping-1]
	_ = x[StateStarting-2]
	_ = x[StateAdopting-3]
	_ = x[StateRunning-4]
	_ = x[StateRestarting-5]
	_ = x[StateExited-6]
	_ = x[StateErrored-7]
	_ = x[StateCleaningError-8]
}

const _State_name = "StoppedStoppingStartingAdoptingRunningRestartingExitedErroredCleaningError"

var _State_index = [...]uint8{0, 7, 15, 23, 31, 38, 48, 54, 61, 74}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionStop-0]
	_ = x[ActionStart-1]
	_ = x[ActionAdopt-2]
	_ = x[ActionRestart-3]
}

const _Action_name = "StopStartAdoptRestart"

var _Action_index = [...]uint8{0, 4, 9, 14, 21}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
