// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: svctl/svctl.proto

package svctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_REGISTERED Status = 0
	Status_STARTED    Status = 1
	Status_STOPPED    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "REGISTERED",
		1: "STARTED",
		2: "STOPPED",
	}
	Status_value = map[string]int32{
		"REGISTERED": 0,
		"STARTED":    1,
		"STOPPED":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_svctl_svctl_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_svctl_svctl_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_svctl_svctl_proto_rawDescGZIP(), []int{0}
}

type ServerOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ServerOpts) Reset() {
	*x = ServerOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svctl_svctl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerOpts) ProtoMessage() {}

func (x *ServerOpts) ProtoReflect() protoreflect.Message {
	mi := &file_svctl_svctl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerOpts.ProtoReflect.Descriptor instead.
func (*ServerOpts) Descriptor() ([]byte, []int) {
	return file_svctl_svctl_proto_rawDescGZIP(), []int{0}
}

func (x *ServerOpts) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=svctl.Status" json:"status,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svctl_svctl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_svctl_svctl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_svctl_svctl_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServerInfo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_REGISTERED
}

var File_svctl_svctl_proto protoreflect.FileDescriptor

var file_svctl_svctl_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2f, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x47, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x25,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x32, 0x9e, 0x01, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x11,
	0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x73, 0x1a, 0x11, 0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x11,
	0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x73, 0x1a, 0x11, 0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x11, 0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4f, 0x70, 0x74, 0x73, 0x1a, 0x11, 0x2e, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x6f, 0x6e, 0x2d, 0x67,
	0x67, 0x2f, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x2f, 0x73, 0x76, 0x63, 0x74, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svctl_svctl_proto_rawDescOnce sync.Once
	file_svctl_svctl_proto_rawDescData = file_svctl_svctl_proto_rawDesc
)

func file_svctl_svctl_proto_rawDescGZIP() []byte {
	file_svctl_svctl_proto_rawDescOnce.Do(func() {
		file_svctl_svctl_proto_rawDescData = protoimpl.X.CompressGZIP(file_svctl_svctl_proto_rawDescData)
	})
	return file_svctl_svctl_proto_rawDescData
}

var file_svctl_svctl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svctl_svctl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_svctl_svctl_proto_goTypes = []interface{}{
	(Status)(0),        // 0: svctl.Status
	(*ServerOpts)(nil), // 1: svctl.ServerOpts
	(*ServerInfo)(nil), // 2: svctl.ServerInfo
}
var file_svctl_svctl_proto_depIdxs = []int32{
	0, // 0: svctl.ServerInfo.status:type_name -> svctl.Status
	1, // 1: svctl.Servers.Start:input_type -> svctl.ServerOpts
	1, // 2: svctl.Servers.Stop:input_type -> svctl.ServerOpts
	1, // 3: svctl.Servers.Register:input_type -> svctl.ServerOpts
	2, // 4: svctl.Servers.Start:output_type -> svctl.ServerInfo
	2, // 5: svctl.Servers.Stop:output_type -> svctl.ServerInfo
	2, // 6: svctl.Servers.Register:output_type -> svctl.ServerInfo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_svctl_svctl_proto_init() }
func file_svctl_svctl_proto_init() {
	if File_svctl_svctl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svctl_svctl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svctl_svctl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svctl_svctl_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svctl_svctl_proto_goTypes,
		DependencyIndexes: file_svctl_svctl_proto_depIdxs,
		EnumInfos:         file_svctl_svctl_proto_enumTypes,
		MessageInfos:      file_svctl_svctl_proto_msgTypes,
	}.Build()
	File_svctl_svctl_proto = out.File
	file_svctl_svctl_proto_rawDesc = nil
	file_svctl_svctl_proto_goTypes = nil
	file_svctl_svctl_proto_depIdxs = nil
}
