// Code generated by "stringer -type=StateT,Action -linecomment -output=types_string.go"; DO NOT EDIT.

package fsm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateTStopped-0]
	_ = x[StateTRunning-1]
	_ = x[StateTRestarting-2]
	_ = x[StateTUpdating-3]
	_ = x[StateTErrored-4]
}

const _StateT_name = "StoppedRunningRestartingUpdatingErrored"

var _StateT_index = [...]uint8{0, 7, 14, 24, 32, 39}

func (i StateT) String() string {
	if i < 0 || i >= StateT(len(_StateT_index)-1) {
		return "StateT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateT_name[_StateT_index[i]:_StateT_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionStop-0]
	_ = x[ActionStart-1]
	_ = x[ActionAdopt-2]
	_ = x[ActionRestart-3]
}

const _Action_name = "StopStartAdoptRestart"

var _Action_index = [...]uint8{0, 4, 9, 14, 21}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
